spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            logger-level: full
            read-timeout: 5000
            connect-timeout: 3000
          service-product:
            logger-level: full
            read-timeout: 5000
            connect-timeout: 3000
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
      eager: true
      web-context-unify: false
feign:
  sentinel:
    enabled: true