server:
  port: 9000
spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      config:
        import-check:
          enabled: false
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
      eager: true
  application:
    name: service-product